#BASIC PROBLEMS..

#1. List all unique cities where customers are located
SELECT DISTINCT customer_city
FROM customers
ORDER BY customer_city;

#2. Count the number of orders placed in 2017
SELECT COUNT(*) AS total_orders_2017
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2017;

#3. Find the total sales per category
SELECT
    p.product_category AS category,
    SUM(oi.price) AS total_sales
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_category
ORDER BY total_sales DESC;

#4. Calculate the percentage of orders paid in installments
SELECT
    (COUNT(DISTINCT CASE 
        WHEN payment_installments > 1 THEN order_id 
     END) * 100.0 / COUNT(DISTINCT order_id)) 
     AS installment_percentage
FROM payments;

#5. Count the number of customers from each state
SELECT
    customer_state,
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM customers
GROUP BY customer_state
ORDER BY total_customers DESC;


#INTERMEDIATE PROBLEMS..

#1. Calculate the number of orders per month in 2018
SELECT
    MONTH(order_purchase_timestamp) AS month,
    COUNT(order_id) AS total_orders
FROM orders
WHERE YEAR(order_purchase_timestamp) = 2018
GROUP BY MONTH(order_purchase_timestamp)
ORDER BY month;

#2. Find the average number of products per order, grouped by customer city
SELECT
    customer_city,
    AVG(order_product_count) AS avg_products_per_order
FROM (
    SELECT
        o.order_id,
        customer_city,
        COUNT(oi.product_id) AS order_product_count
    FROM orders o
    JOIN customers c
        ON o.customer_id = c.`ï»¿customer_id`
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.order_id, customer_city
) sub
GROUP BY customer_city
ORDER BY avg_products_per_order DESC;

#3. Calculate the percentage of total revenue contributed by each product category
SELECT
    p.product_category AS category,
    ROUND(
        SUM(oi.price) * 100.0 /
        (SELECT SUM(price) FROM order_items),
        2
    ) AS revenue_percentage
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_category
ORDER BY revenue_percentage DESC;

#4. Identify the correlation between product price and number of times purchased
SELECT
    oi.product_id,
    AVG(oi.price) AS avg_price,
    COUNT(oi.order_id) AS purchase_count
FROM order_items oi
GROUP BY oi.product_id;

#5. Calculate total revenue generated by each seller and rank them
SELECT
    s.seller_id,
    SUM(price) AS total_revenue,
    RANK() OVER (ORDER BY SUM(o.price) DESC) AS revenue_rank
FROM sellers s
JOIN order_items o
    ON s.seller_id = o.product_id
GROUP BY s.seller_id
ORDER BY revenue_rank;


#ADVANCED PROBLEMS..

#1. Moving average of order values for each customer
WITH order_values AS (
    SELECT
        o.order_id,
        o.customer_id,
        o.order_purchase_timestamp,
        SUM(oi.price) AS order_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.order_id, o.customer_id, o.order_purchase_timestamp
)
SELECT
    customer_id,
    order_purchase_timestamp,
    order_value,
    AVG(order_value) OVER (
        PARTITION BY customer_id
        ORDER BY order_purchase_timestamp
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS moving_avg_order_value
FROM order_values;

#2. Cumulative sales per month for each year
WITH monthly_sales AS (
    SELECT
        YEAR(o.order_purchase_timestamp) AS year,
        MONTH(o.order_purchase_timestamp) AS month,
        SUM(oi.price) AS monthly_sales
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY year, month
)
SELECT
    year,
    month,
    monthly_sales,
    SUM(monthly_sales) OVER (
        PARTITION BY year
        ORDER BY month
    ) AS cumulative_sales
FROM monthly_sales
ORDER BY year, month;

#3. Year-over-Year (YoY) growth rate of total sales
WITH yearly_sales AS (
    SELECT
        YEAR(o.order_purchase_timestamp) AS year,
        SUM(oi.price) AS total_sales
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY year
)
SELECT
    year,
    total_sales,
    ROUND(
        (total_sales - LAG(total_sales) OVER (ORDER BY year))
        * 100.0 /
        LAG(total_sales) OVER (ORDER BY year),
        2
    ) AS yoy_growth_percentage
FROM yearly_sales;

#4. Customer retention rate
WITH first_orders AS (
    SELECT
        c.customer_unique_id,
        MIN(o.order_purchase_timestamp) AS first_order_date
    FROM orders o
    JOIN customers c
        ON o.customer_id = c.`ï»¿customer_id`
    GROUP BY c.customer_unique_id
),
repeat_customers AS (
    SELECT DISTINCT
        fo.customer_unique_id
    FROM orders o
    JOIN customers c
        ON o.customer_id = c.`ï»¿customer_id`
    JOIN first_orders fo
        ON c.customer_unique_id = fo.customer_unique_id
    WHERE o.order_purchase_timestamp > fo.first_order_date
      AND o.order_purchase_timestamp <= DATE_ADD(fo.first_order_date, INTERVAL 6 MONTH)
)
SELECT
    ROUND(
        COUNT(DISTINCT rc.customer_unique_id) * 100.0 /
        COUNT(DISTINCT fo.customer_unique_id),
        2
    ) AS retention_rate_percentage
FROM first_orders fo
LEFT JOIN repeat_customers rc
    ON fo.customer_unique_id = rc.customer_unique_id;

#5. Top 3 customers by spending in each year
WITH yearly_customer_spend AS (
    SELECT
        YEAR(o.order_purchase_timestamp) AS year,
        c.customer_unique_id,
        SUM(oi.price) AS total_spent
    FROM orders o
    JOIN customers c
        ON o.customer_id = c.`ï»¿customer_id`
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY year, c.customer_unique_id
),
ranked_customers AS (
    SELECT *,
           RANK() OVER (
               PARTITION BY year
               ORDER BY total_spent DESC
           ) AS rank_in_year
    FROM yearly_customer_spend
)
SELECT
    year,
    customer_unique_id,
    total_spent
FROM ranked_customers
WHERE rank_in_year <= 3
ORDER BY year, rank_in_year;